import React, { useState } from 'react';
import { Sparkles, Bot, ExternalLink, Ruler, Scale, ShieldAlert, Award, Compass, Loader2 } from 'lucide-react';
import { chromeAI } from '../../services/ai/chromeAIService';

export function OverviewTab({ creature }) {
  const [aiSummary, setAiSummary] = useState(null);
  const [isLoadingAI, setIsLoadingAI] = useState(false);

  const handleSimplify = async () => {
    setIsLoadingAI(true);
    try {
      const result = await chromeAI.translateTaxonomy(creature.description, creature.commonName);
      setAiSummary(result);
    } catch (err) {
      console.warn('AI summary failed:', err);
    } finally {
      setIsLoadingAI(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* On-Device AI Simplifier Showcase */}
      <div style={{
        background: 'linear-gradient(135deg, rgba(0, 240, 255, 0.08) 0%, rgba(168, 85, 247, 0.08) 100%)',
        border: '1px solid var(--border-glow)',
        borderRadius: 'var(--radius-md)',
        padding: '20px',
        position: 'relative'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px', flexWrap: 'wrap', gap: '8px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{
              display: 'inline-flex',
              padding: '6px',
              borderRadius: '8px',
              background: 'var(--accent-primary)',
              color: '#050B10'
            }}>
              <Sparkles size={16} />
            </span>
            <h4 style={{ fontSize: '1rem', fontWeight: 700, margin: 0 }}>
              AI Science Communicator
            </h4>
          </div>

          <button
            onClick={handleSimplify}
            disabled={isLoadingAI}
            className="btn btn-primary"
            style={{ fontSize: '0.82rem', padding: '6px 14px' }}
            id="btn-ai-simplify"
          >
            {isLoadingAI ? (
              <>
                <Loader2 size={14} className="animate-spin-slow" />
                <span>Translating with AI...</span>
              </>
            ) : (
              <>
                <Bot size={14} />
                <span>Simplify with AI</span>
              </>
            )}
          </button>
        </div>

        {aiSummary ? (
          <div style={{
            background: 'rgba(5, 11, 16, 0.8)',
            padding: '16px',
            borderRadius: 'var(--radius-sm)',
            border: '1px solid rgba(255, 255, 255, 0.08)'
          }}>
            <p style={{ fontSize: '0.95rem', lineHeight: 1.6, color: 'var(--text-primary)', marginBottom: '8px' }}>
              "{aiSummary.text}"
            </p>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.72rem', color: 'var(--text-muted)' }}>
              <span style={{
                width: '6px',
                height: '6px',
                borderRadius: '50%',
                background: aiSummary.isNativeAI ? '#10B981' : '#38BDF8'
              }} />
              <span>
                {aiSummary.isNativeAI ? 'Processed by Chrome On-Device Gemini Nano' : 'Generated by Procedural Science Engine'}
              </span>
            </div>
          </div>
        ) : (
          <p style={{ fontSize: '0.88rem', color: 'var(--text-secondary)', margin: 0 }}>
            Click <strong>"Simplify with AI"</strong> to convert this creature's complex biological description into a fun, museum-grade summary in real-time.
          </p>
        )}
      </div>

      {/* Narrative Section */}
      <div>
        <h4 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '10px' }}>
          Evolutionary & Ecological Profile
        </h4>
        <p style={{ fontSize: '0.95rem', lineHeight: 1.7, color: 'var(--text-secondary)' }}>
          {creature.description}
        </p>
      </div>

      {/* Morphometrics & Key Stats Grid */}
      <div>
        <h4 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '14px' }}>
          Biological Metrics
        </h4>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
          gap: '12px'
        }}>
          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '14px'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-muted)', fontSize: '0.75rem', marginBottom: '6px' }}>
              <Ruler size={14} />
              <span>SIZE / LENGTH</span>
            </div>
            <div style={{ fontSize: '1.15rem', fontWeight: 700, color: 'var(--text-primary)' }}>
              {creature.stats?.lengthMeters ? `${creature.stats.lengthMeters} m` : 'Variable'}
            </div>
          </div>

          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '14px'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-muted)', fontSize: '0.75rem', marginBottom: '6px' }}>
              <Scale size={14} />
              <span>MASS</span>
            </div>
            <div style={{ fontSize: '1.15rem', fontWeight: 700, color: 'var(--text-primary)' }}>
              {creature.stats?.weightKg != null
                ? creature.stats.weightKg >= 1000
                  ? `${(creature.stats.weightKg / 1000).toFixed(1)} tons`
                  : `${creature.stats.weightKg} kg`
                : 'Microscopic'}
            </div>
          </div>

          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '14px'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-muted)', fontSize: '0.75rem', marginBottom: '6px' }}>
              <ShieldAlert size={14} style={{ color: '#F87171' }} />
              <span>THREAT RATING</span>
            </div>
            <div style={{ fontSize: '1.15rem', fontWeight: 700, color: '#F87171' }}>
              {creature.stats?.dangerLevel || 5} / 10
            </div>
          </div>

          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '14px'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-muted)', fontSize: '0.75rem', marginBottom: '6px' }}>
              <Award size={14} style={{ color: 'var(--accent-primary)' }} />
              <span>RARITY INDEX</span>
            </div>
            <div style={{ fontSize: '1.15rem', fontWeight: 700, color: 'var(--accent-primary)' }}>
              {creature.stats?.rarityScore || 90} / 100
            </div>
          </div>
        </div>
      </div>

      {/* Scientific Taxonomy Breakdown */}
      {creature.taxonomy && (
        <div>
          <h4 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '14px' }}>
            Taxonomic Classification
          </h4>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
            gap: '10px',
            background: 'rgba(5, 11, 16, 0.5)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '16px'
          }}>
            {Object.entries(creature.taxonomy).map(([rank, name]) => (
              <div key={rank}>
                <div style={{ fontSize: '0.72rem', textTransform: 'uppercase', color: 'var(--text-muted)', letterSpacing: '0.05em' }}>
                  {rank}
                </div>
                <div style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--text-primary)' }}>
                  {name}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* External Reference Link */}
      {creature.wikiUrl && (
        <div style={{ display: 'flex', justifyContent: 'flex-end', paddingTop: '8px' }}>
          <a
            href={creature.wikiUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="btn btn-secondary"
            style={{ fontSize: '0.85rem' }}
          >
            <span>Read on Wikipedia</span>
            <ExternalLink size={14} />
          </a>
        </div>
      )}
    </div>
  );
}
